### PR TITLE
Add Vault to Wallet & Create `key-management` package

### PR DESCRIPTION
**Pull request by teddyjfpender**
# Add Vault to Wallet & Create `key-management` package

In progress.

Lots of additions.

Significant amount of inspiration from `cardano-js-sdk`.

### CODE REVIEW

**Comment by teddyjfpender** [comment]
@mrcnk Currently, there is one failing test that I'm looking to fix today on decrypting the coin-type private key. Otherwise, this is a large addition 😅

**Comment by teddyjfpender** [comment]
New method from `signTransaction` has been added but the verification test for transaction signing is failing.

**Comment by teddyjfpender** [comment]
@mrcnk The first implementation of `keyAgent` using stores is done. Currently, the only functionality available is `restoreWallet`.

**Review by mrcnk — APPROVED** [review]
romano-fabrizio

**Pull request merged**
