### PR TITLE
Add Word Number Labels to Mnemonic Inputs in Wallet Restoration Flow

### PR DESCRIPTION
**Pull request by aliraza556**
### Problem:
- The word number label disappears when the user types in the mnemonic input field.

closes: #190

## Issue ticket number and link:
- **Ticket Number:** [ 190 ]
- **Link:** [ https://github.com/palladians/pallad/issues/190 ]

### Evidence:

https://www.loom.com/share/7cc9a86b55ce4457ba6b943530f5b633

image

### Acceptance Criteria
- [x]   Each Seed Import input should have a label inside the input with an according word number.
- [x] It should work fine on smaller side panels - inputs should be responsive.

### CODE REVIEW

**Comment by aliraza556** [comment]
Hi @mrcnk Please review this PR.

**Comment by mrcnk** [comment]
Hi @aliraza556, it's almost perfect, can you just make sure the label has enough of spacing for double digit numbers? It's a little too close.
CleanShot 2024-08-21 at 11 10 04@2x
When it's fixed I'm gonna merge and let you know how we do bounty pay outs with https://astromina.org/.

**Comment by aliraza556** [comment]
> When it's fixed I'm gonna merge and let you know how we do bounty pay outs with https://astromina.org/.

@mrcnk Ok I fix it and then ping you.

**Comment by aliraza556** [comment]
Hi @mrcnk, Please merge this PR.

image

**Comment by aliraza556** [comment]
> Hi @aliraza556, it's almost perfect, can you just make sure the label has enough of spacing for double digit numbers? It's a little too close. CleanShot 2024-08-21 at 11 10 04@2x When it's fixed I'm gonna merge and let you know how we do bounty pay outs with https://astromina.org/.

@mrcnk Fixed

**Comment by mrcnk** [comment]
@aliraza556 now it's the other way around, the single digit number labels are too close 😅

CleanShot 2024-08-21 at 14 08 00

**Comment by aliraza556** [comment]
> @aliraza556 now it's the other way around, the single digit number labels are too close 😅
> 
> CleanShot 2024-08-21 at 14 08 00

ok I try to fix it

**Comment by aliraza556** [comment]
@mrcnk Done:

image

**Comment by mrcnk** [comment]
@aliraza556 please format the code with "pnpm format:unsafe" and push again, that should make it complete and bounty will be on the way to you

**Comment by aliraza556** [comment]
@mrcnk Please approve the workflows

**Comment by aliraza556** [comment]
Hi @mrcnk, How i get payment any idea?

**Pull request merged**
