### PR TITLE
Add internationalization and replace all hardcoded labels with i18n entries

### PR DESCRIPTION
**Pull request by ManyRios**
## Describe changes
 Added react-i18next dependency for packages/features.
 Added all necessary config files for the i18next library.
 Extracted all necessary i18n entries from hardcoded labels in Pallad to locales/en.json

## Ticket or discussion link
https://github.com/palladians/pallad/issues/194

All the labels has been changed in packages/features.

### CODE REVIEW

**Comment by ManyRios** [comment]
@mrcnk Please review...

**Comment by mrcnk** [comment]
Hi @ManyRios, the wallet doesn't seem to work when I built it:
CleanShot 2024-08-30 at 21 53 49@2x

**Comment by ManyRios** [comment]
@mrcnk  I dont have conflicts... please check again 
image

**Comment by ManyRios** [comment]
Hey @mrcnk please review this PR

**Pull request closed without merging**
