### PR TITLE
Add internationalization and replace all hardcoded labels with i18n entries

### PR DESCRIPTION
**Pull request by ManyRios**
## Describe changes

 Added react-i18next dependency for packages/features.
 Added all necessary config files for the i18next library.
 Extracted all necessary i18n entries from hardcoded labels in Pallad to locales/en.json

## Ticket or discussion link

https://github.com/palladians/pallad/issues/194

All the labels has been changed in packages/features. 

@mrcnk

### CODE REVIEW

**Comment by ManyRios** [comment]
@mrcnk  Please review

**Comment by ManyRios** [comment]
Hey @mrcnk

**Comment by ManyRios** [comment]
@mrcnk please review this PR

**Review by mrcnk — APPROVED** [review]

**Comment by mrcnk** [comment]
@all-contributors please add @ManyRios for code

**Pull request merged**
