### PR TITLE
Portfolio value change calculation is broken when using Mina values

### PR DESCRIPTION
**Pull request by aliraza556**
### Problem:
- When using Mina values on Dashboard, the daily change +0.02 (24h) is broken, displaying pretty much the same value all the time.

closes: #198

## Issue ticket number and link:
- **Ticket Number:** [ 198 ]
- **Link:** [ https://github.com/palladians/pallad/issues/198 ]

### Acceptance Criteria
- [x]  The value reflects an actual fiat change, but in Mina.

### CODE REVIEW

**Comment by aliraza556** [comment]
Hi @mrcnk, Please review this PR.

**Comment by mrcnk** [comment]
Hey, just checked and:
- First there's an additional, unnecessary minus for negative values.
- Value is still fixed at -0.03, no matter of portfolio size.
CleanShot 2024-08-27 at 11 57 27

**Comment by aliraza556** [comment]
> Hey, just checked and:
> 
> * First there's an additional, unnecessary minus for negative values.
> * Value is still fixed at -0.03, no matter of portfolio size.
>   CleanShot 2024-08-27 at 11 57 27

@mrcnk Please review this PR: I have fixed
image

**Comment by mrcnk** [comment]
@aliraza556 It's now displaying fiat values both for fiat and Mina. For Mina it should display Mina value, so if for example the price of Mina is 50c, it should be:
```
Mina Change Value = Fiat Change Value / Fiat Price
In example: Fiat Change Value = 100 USD, Fiat Price = 50c
Mina Change Value = 100 USD / 0.5
Mina Change Value = 200 Mina
```

**Comment by aliraza556** [comment]
> @aliraza556 It's now displaying fiat values both for fiat and Mina. For Mina it should display Mina value, so if for example the price of Mina is 50c, it should be:
> 
> ```
> Mina Change Value = Fiat Change Value / Fiat Price
> In example: Fiat Change Value = 100 USD, Fiat Price = 50c
> Mina Change Value = 100 USD / 0.5
> Mina Change Value = 200 Mina
> ```

@mrcnk Please review it i have fixed

**Review by mrcnk — APPROVED** [review]

**Comment by mrcnk** [comment]
@aliraza556 it's working fine now, can you just format the code and push again?

**Comment by aliraza556** [comment]
> @aliraza556 it's working fine now, can you just format the code and push again?

@mrcnk Ok

**Comment by aliraza556** [comment]
@mrcnk Done

**Pull request merged**
